ktor {
    application {
        modules = [ com.example.catlifepet.server.ApplicationKt.module ]
    }
    deployment {
        host = "0.0.0.0"
        host = ${?HOST}
        port = 8080
        port = ${?PORT}
    }
}

catlifepet {
    environment = "development"
    environment = ${?CATLIFEPET_ENV}
    publicBaseUrl = ${?CATLIFEPET_PUBLIC_BASE_URL}
    databaseUrl = ${?DATABASE_URL}
    jwtSecret = ${?CATLIFEPET_JWT_SECRET}
    openAiApiKey = ${?OPENAI_API_KEY}
}
